package ac.ifunpas.psbk.pojo;
// Generated May 20, 2020, 2:30:58 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pendapatan generated by hbm2java
 */
@Entity
@Table(name = "pendapatan", catalog = "moneymanager")
public class Pendapatan implements java.io.Serializable {

	private String idPendapatan;
	private Date tanggal;
	private int jumlah;
	private String catatan;
	private Set<Saldobalance> saldobalances = new HashSet<Saldobalance>(0);

	public Pendapatan() {
	}

	public Pendapatan(String idPendapatan, Date tanggal, int jumlah, String catatan) {
		this.idPendapatan = idPendapatan;
		this.tanggal = tanggal;
		this.jumlah = jumlah;
		this.catatan = catatan;
	}

	public Pendapatan(String idPendapatan, Date tanggal, int jumlah, String catatan, Set<Saldobalance> saldobalances) {
		this.idPendapatan = idPendapatan;
		this.tanggal = tanggal;
		this.jumlah = jumlah;
		this.catatan = catatan;
		this.saldobalances = saldobalances;
	}

	@Id

	@Column(name = "id_pendapatan", unique = true, nullable = false, length = 11)
	public String getIdPendapatan() {
		return this.idPendapatan;
	}

	public void setIdPendapatan(String idPendapatan) {
		this.idPendapatan = idPendapatan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tanggal", nullable = false, length = 10)
	public Date getTanggal() {
		return this.tanggal;
	}

	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

	@Column(name = "jumlah", nullable = false)
	public int getJumlah() {
		return this.jumlah;
	}

	public void setJumlah(int jumlah) {
		this.jumlah = jumlah;
	}

	@Column(name = "catatan", nullable = false, length = 200)
	public String getCatatan() {
		return this.catatan;
	}

	public void setCatatan(String catatan) {
		this.catatan = catatan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pendapatan")
	public Set<Saldobalance> getSaldobalances() {
		return this.saldobalances;
	}

	public void setSaldobalances(Set<Saldobalance> saldobalances) {
		this.saldobalances = saldobalances;
	}

}
