package ac.ifunpas.psbk.pojo;
// Generated May 20, 2020, 2:30:58 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pengeluaran generated by hbm2java
 */
@Entity
@Table(name = "pengeluaran", catalog = "moneymanager")
public class Pengeluaran implements java.io.Serializable {

	private String idPengeluaran;
	private Date tanggalPilih;
	private int transportasi;
	private int makanan;
	private int kesehatan;
	private int kecantikan;
	private int pakaian;
	private int komunikasi;
	private int lainnya;
	private int jumlah;
	private String catatan;
	private Set<Saldobalance> saldobalances = new HashSet<Saldobalance>(0);

	public Pengeluaran() {
	}

	public Pengeluaran(String idPengeluaran, Date tanggalPilih, int transportasi, int makanan, int kesehatan,
			int kecantikan, int pakaian, int komunikasi, int lainnya, int jumlah, String catatan) {
		this.idPengeluaran = idPengeluaran;
		this.tanggalPilih = tanggalPilih;
		this.transportasi = transportasi;
		this.makanan = makanan;
		this.kesehatan = kesehatan;
		this.kecantikan = kecantikan;
		this.pakaian = pakaian;
		this.komunikasi = komunikasi;
		this.lainnya = lainnya;
		this.jumlah = jumlah;
		this.catatan = catatan;
	}

	public Pengeluaran(String idPengeluaran, Date tanggalPilih, int transportasi, int makanan, int kesehatan,
			int kecantikan, int pakaian, int komunikasi, int lainnya, int jumlah, String catatan,
			Set<Saldobalance> saldobalances) {
		this.idPengeluaran = idPengeluaran;
		this.tanggalPilih = tanggalPilih;
		this.transportasi = transportasi;
		this.makanan = makanan;
		this.kesehatan = kesehatan;
		this.kecantikan = kecantikan;
		this.pakaian = pakaian;
		this.komunikasi = komunikasi;
		this.lainnya = lainnya;
		this.jumlah = jumlah;
		this.catatan = catatan;
		this.saldobalances = saldobalances;
	}

	@Id

	@Column(name = "id_pengeluaran", unique = true, nullable = false, length = 11)
	public String getIdPengeluaran() {
		return this.idPengeluaran;
	}

	public void setIdPengeluaran(String idPengeluaran) {
		this.idPengeluaran = idPengeluaran;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tanggal_pilih", nullable = false, length = 10)
	public Date getTanggalPilih() {
		return this.tanggalPilih;
	}

	public void setTanggalPilih(Date tanggalPilih) {
		this.tanggalPilih = tanggalPilih;
	}

	@Column(name = "transportasi", nullable = false)
	public int getTransportasi() {
		return this.transportasi;
	}

	public void setTransportasi(int transportasi) {
		this.transportasi = transportasi;
	}

	@Column(name = "makanan", nullable = false)
	public int getMakanan() {
		return this.makanan;
	}

	public void setMakanan(int makanan) {
		this.makanan = makanan;
	}

	@Column(name = "kesehatan", nullable = false)
	public int getKesehatan() {
		return this.kesehatan;
	}

	public void setKesehatan(int kesehatan) {
		this.kesehatan = kesehatan;
	}

	@Column(name = "kecantikan", nullable = false)
	public int getKecantikan() {
		return this.kecantikan;
	}

	public void setKecantikan(int kecantikan) {
		this.kecantikan = kecantikan;
	}

	@Column(name = "pakaian", nullable = false)
	public int getPakaian() {
		return this.pakaian;
	}

	public void setPakaian(int pakaian) {
		this.pakaian = pakaian;
	}

	@Column(name = "komunikasi", nullable = false)
	public int getKomunikasi() {
		return this.komunikasi;
	}

	public void setKomunikasi(int komunikasi) {
		this.komunikasi = komunikasi;
	}

	@Column(name = "lainnya", nullable = false)
	public int getLainnya() {
		return this.lainnya;
	}

	public void setLainnya(int lainnya) {
		this.lainnya = lainnya;
	}

	@Column(name = "jumlah", nullable = false)
	public int getJumlah() {
		return this.jumlah;
	}

	public void setJumlah(int jumlah) {
		this.jumlah = jumlah;
	}

	@Column(name = "catatan", nullable = false, length = 128)
	public String getCatatan() {
		return this.catatan;
	}

	public void setCatatan(String catatan) {
		this.catatan = catatan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pengeluaran")
	public Set<Saldobalance> getSaldobalances() {
		return this.saldobalances;
	}

	public void setSaldobalances(Set<Saldobalance> saldobalances) {
		this.saldobalances = saldobalances;
	}

}
