package ac.ifunpas.psbk.pojo;
// Generated May 20, 2020, 2:30:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Saldobalance generated by hbm2java
 */
@Entity
@Table(name = "saldobalance", catalog = "moneymanager")
public class Saldobalance implements java.io.Serializable {

	private String id;
	private Pendapatan pendapatan;
	private Pengeluaran pengeluaran;
	private int jumlah;
	private Set<User> users = new HashSet<User>(0);

	public Saldobalance() {
	}

	public Saldobalance(String id, int jumlah) {
		this.id = id;
		this.jumlah = jumlah;
	}

	public Saldobalance(String id, Pendapatan pendapatan, Pengeluaran pengeluaran, int jumlah, Set<User> users) {
		this.id = id;
		this.pendapatan = pendapatan;
		this.pengeluaran = pengeluaran;
		this.jumlah = jumlah;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 11)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pendapatan")
	public Pendapatan getPendapatan() {
		return this.pendapatan;
	}

	public void setPendapatan(Pendapatan pendapatan) {
		this.pendapatan = pendapatan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pengeluaran")
	public Pengeluaran getPengeluaran() {
		return this.pengeluaran;
	}

	public void setPengeluaran(Pengeluaran pengeluaran) {
		this.pengeluaran = pengeluaran;
	}

	@Column(name = "jumlah", nullable = false)
	public int getJumlah() {
		return this.jumlah;
	}

	public void setJumlah(int jumlah) {
		this.jumlah = jumlah;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "saldobalance")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
